### ISSUE TITLE
Add navbar

### ISSUE THREAD

**Issue by markbello** [markbello/gatsbyjs-nyc#8]
We currently have no navigation because flexbox doesn't play well with our logo. Perhaps we'll have to simplify the logo by rendering without higher-order components. Ultimately we'd probably want the logo to be in SVG format anyway, in which case we wouldn't really need the benefits of `gatsby-image`

**Comment by eddgr** [comment]
Sent a PR for this: https://github.com/markbello/gatsbyjs-nyc/pull/10

**Comment by markbello** [comment]
@eddgr great work, and thank you for your contribution!
